### ISSUE TITLE
Build is broken, mac installer is now broken, lua must be dynamically linked

### ISSUE THREAD

**Issue by paulsapps** [q-gears/q-gears#41]
if APPLE must come BEFORE if UNIX because on mac UNIX is also true.

Lua must be dynamically linked else the lua state is not shared across modules. 

And currently the build is failing due to invalid luajit submodule.

P.S You should always create pull requests first to avoid situations like this

**Comment by sithlord48** [comment]
we can use  if(CMAKE_SYSTEM_NAME MATCHES "Linux") for the detection of linux since it will only be true on that platform. 

i think we should look into using the system provided versions of all dependcies at very least on linux. i have not commited this since it requires changes to each file that includes tinyxml . the include will need to be changed to #include<tinyxml> from #include <tinyxml/tinyxml>

**Comment by paulsapps** [comment]
"changed to #include from #include" eh? Using UNIX is fine so long as its done after the APPLE check otherwise it won't detected correctly. I've rolled back the build breaking changes for now

**Comment by sithlord48** [comment]
oops it striped my includes :(
the current include for tinyxml is #include< tinyxml / tinyxml.h >   it would need to be changed to #include < tinyxml.h > there are a few file <10 iirc that would require this change.  one is QGearsMain/include/core/XmlFile.h

**Comment by paulsapps** [comment]
Closing - build is now fixed and lua is dynamic as that change was reverted.
